### ISSUE TITLE
Export / Import Job configurations as JSON

### ISSUE THREAD

**Issue by alejoe91** [scratchrealm/protocaas#115]
A user might want to save a preset of parameters for a specificic app.

These could be saved in the project folder and rendered as a dropdown if available

**Comment by luiztauffer** [comment]
Since all jobs parameters are stored in the database, I believe we can generalize this with two functionalities:

1. Export to JSON – this would contain all relevant information to fully reproduce a given job:

```
{
    input: {… input files and configuration …}
    resources:  {… resources configuration …}
    processor: {… processor parameters …}
}
```

2. Load from JSON – when submitting new jobs, users could import the preset for input, resources and processor from these files

**Comment by magland** [comment]
@luiztauffer @alejoe91 

I implemented this somewhat differently that proposed (for now).

But the upshot is... there are now a "save parameters" and "load parameters" buttons at the top of the parameter input form.

It saves the parameters in the "parameter-sets" folder of the project.

![image](https://github.com/flatironinstitute/dendro/assets/3679296/256bab02-a46d-4afb-97b5-856e498dd270)

**Comment by luiztauffer** [comment]
@magland this looks great, thanks!
I just tried it, would it be possible to load the parameters from a json file? It could be the one we can export from the Job panel for example. In this way people can easily share and re-use their job configurations in different Projects

**Comment by magland** [comment]
@luiztauffer This should be working now. See #121.
