### ISSUE TITLE
Processors parameterization

### ISSUE THREAD

**Issue by luiztauffer** [scratchrealm/protocaas#9]
We should think and define what features we want to accomplish with our parameterization format. Here’s a tentative list:
- Define at least these 4 argument props: name, type, default value and description.
- We should be able to map from definition to json schema without having to parse business logic code.
- If possible to translate other validation rules to json schema, it would be great (regex, less/greater than, etc…).
- Composability and nesting of typing models/interfaces
- Allow specifying secret=True  for parameters that are not to be include anywhere (e.g., in the GUI) except for during run time to the containerized job.
- Given those features, be a straightforward and easy to use as possible

**Comment by magland** [comment]
@luiztauffer 

How about this

https://github.com/scratchrealm/pc-spike-sorting/blob/processor-spec-proposal/mountainsort5/main.py
https://github.com/scratchrealm/pc-spike-sorting/blob/processor-spec-proposal/mountainsort5/protocaas_sdk_proposed_imports.py

I know it's similar to pydantic, but I think our requirements warrant a more specialized solution.

The one tricky thing I needed to do was to have parameter and parameter_group explicitly return the Any type to keep linters happy. You'll see comments in the code.

**Comment by luiztauffer** [comment]
thanks for looking at this @magland! With this we gain model composability, which is much necessary! 
But at first glance it became a complex mix of different things, it got me a bit confused… there are two points I’d like to understand better:

1. Yes it looks a lot like Pydantic, so why not use it, instead? Dataclass doesn’t provide all the features we want (extra props, in this case), so we’re amending it with our own `parameter` and `parameter_group` classes instead. We’ll also have to maintain our own set of validators and translator to json schema. I believe we can get all of that for free with Pydantic, or I’m missing something?


2. How would you feel if we use classes for Processors? Tentative example:

```python
import protocaas as pr


class Mountainsort5(pr.BaseProcessor):
    name = 'mountainsort5'
    version = '0.1.0'
    help = "Mountainsort5 spike sorting processor"
    attributes = {
        'wip': True,
        'label': 'Mountainsort 5',
    }
    tags = ['spike_sorting', 'spike_sorter']

    def run(input: pr.InputFile, output: pr.OutputFile, parameters: Mountainsort5Parameters):
        ...


app.add_processor(Mountainsort5)
```

This somehow feels more intuitive to me than using different decorators… what do you think?
Is there a specific functionality we’re gaining with the decorators approach?

**Comment by magland** [comment]
@luiztauffer 

I agree that using a class is better. Here's the next iteration

https://github.com/scratchrealm/pc-spike-sorting/blob/processor-spec-proposal/mountainsort5/main.py

https://github.com/scratchrealm/pc-spike-sorting/blob/processor-spec-proposal/mountainsort5/protocaas_sdk_proposed_imports.py

Note there is now a context being passed in, which I think is cleaner.

---

Regarding your pydantic proposal, here are some reasons for not using it (I've outlined some of these in the past)

Here's what I used to have a couple months ago

https://github.com/scratchrealm/neurobass/blob/e429c6441bf1c4f8c680b64f51cac36a74af6c65/python/neurobass/processing_tools/spike_sorting/Mountainsort5ProcessingTool.py#L22-L51

1. Even though you get translation to json schema using pydantic, it's not the one I would use. I tried this and it was difficult to type and parse on the typescript side. And it didn't have all the features I wanted. So I had to parse it and make a neurobass-specific spec, and that was a lot of effort. Maybe I could have done a better job, but it didn't seem trivial at the time. It's not free.

2. We are not planning to support all the features of pydantic (e.g., dynamic validation which would need to be translated and re-implemented on the typescript side), so we'd need to outline/document which subset we do support. And it's not going to be easily enforced**

3. Regarding validation, I don't think it's an issue because the parameters/context coming in will already have been validated on the typescript side. And we can do another validation on the python side as well, it wouldn't be too difficult IMO.

4. I like having choices parameter a lot more than using an Enum, because the Enum needs to be specially handled to convert to a choices list in order to translate into the spec that will be read on the typescript.

5. There are protocaas-specific fields we'll want to support such as "secret", and I'm sure this will grow.

A lot of these arise from the fact that we need to have a system that works on both the typescript and Python sides, and I think we should use a homemade system for that rather than conforming to pydantic, because we're not supporting the full pydantic on the ts side.

**Comment by magland** [comment]
(further edited the new code just now)

**Comment by luiztauffer** [comment]
I like the Context containing input, output definitions and parameters, it’s cleaner and better organized. 
Are we still able to identify the right Context model to be parsed when creating the schemas? Just thought about that now.

Now that we have models as separate entities on their own merits, something to consider is whether we’d like to encourage developers to store them in their own modules/files. That would follow good practices of separation of concerns, and would allow us to import them independently, if ever useful to do so. Just letting my thoughts fly free here, but it would be great if we eventually converge to well-defined structure of the Apps somehow similar to this:

```
/myapp
    /models/        # typing logic comes from here
    /utils/         # business logic comes from here
    /Dockerfile
    /main.py
    /spec.json
```


---

Don’t get me wrong, I think your solution already covers the features we’re imagining and I’m happy to go ahead with it, I just wanted to understand your choice better, because from my point of view it would be a clear disadvantage to go for a homemade solution. 
Pydantic allows creating any extra props, such as secrets for example. I agree the Enum models can be a bit annoying, but they’re not so bad and explicitly define the types of the options, which might eventually be relevant. Most of the times I’m fine with extra burden created on the backend/frontend system if that eases the dev experience when writing apps/processors, and my bias tells me to favor Pydantic here again.

But if Pydantic creates non-trivial difficulties for the Typescript parsing of the schemas, I think this is a good argument to move away from Pydantic, since this is an essential aspect of the project.

**Comment by luiztauffer** [comment]
It's great that we can run other Processors inside Processors, this allows for the SI pipelines to evolve quite well! 
@alejoe91 fyi

potentially, we would want a single SpikeInterface App, with multiple Processors making use of each other as required... do you think that'd be a good way to go about @magland?

**Comment by magland** [comment]
@luiztauffer 

> I like the Context containing input, output definitions and parameters, it’s cleaner and better organized.
Are we still able to identify the right Context model to be parsed when creating the schemas? Just thought about that now.

I was assuming we could, but I haven't tried it yet.

> Now that we have models as separate entities on their own merits, something to consider is whether we’d like to encourage developers to store them in their own modules/files.

Yes I think that would make sense. For now I'm going to keep it in the same module for convenience but at some point it should be easy to move it out. And once we have a collection of processors that work together, we can begin to adopt the type of structure you are proposing.
